[package]
name = "moon"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = {version = "0.10.3", features = ["v4_12"]}
tree-sitter = "0.26.3"
unicode-segmentation = "1.12.0"

[build-dependencies]
cc = "1.2.53"
